package io.github.abdullahkhan118.fieldvalidator.processor

import com.google.devtools.ksp.getDeclaredProperties
import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.symbol.KSAnnotation
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSPropertyDeclaration
import com.google.devtools.ksp.symbol.KSValueArgument
import com.google.devtools.ksp.symbol.Nullability
import com.google.devtools.ksp.validate
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.ksp.toClassName
import com.squareup.kotlinpoet.ksp.writeTo

private const val ANNOTATIONS_PACKAGE = "io.github.abdullahkhan118.fieldvalidator.annotations"
private const val STRING_ANNOTATIONS_PACKAGE = "$ANNOTATIONS_PACKAGE.string"
private const val RUNTIME_PACKAGE = "io.github.abdullahkhan118.fieldvalidator.runtime"

/**
 * Generates a `<ClassName>Validator` object for every class annotated `@Validated`.
 *
 * Each generated validator implements `Validator<ClassName>` and checks the constraint
 * annotations declared on the class's primary-constructor parameters, in declaration order:
 * `@Range`/`@Distinct` from any `annotations.numeric.*` package (Int, Long, Double, Float,
 * Short, Byte), and `@Pattern`/`@Distinct` from `annotations.string`. The first constraint
 * that fails throws a `ValidationException` immediately (fail-fast) — remaining checks and
 * fields are never evaluated for that call.
 */
class ValidatorProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
) : SymbolProcessor {

    /**
     * Called once per KSP round. Resolves all `@Validated` symbols, generates a validator for
     * each one that's fully resolvable, and returns the rest so KSP retries them next round.
     */
    override fun process(resolver: Resolver): List<com.google.devtools.ksp.symbol.KSAnnotated> {
        // Find every declaration annotated @Validated anywhere in the sources for this round.
        val symbols = resolver.getSymbolsWithAnnotation("$ANNOTATIONS_PACKAGE.Validated")

        // `validate()` returns false for symbols KSP can't fully resolve yet (e.g. they depend
        // on a type still being generated by another processor/round). Split those off so we
        // only generate code for symbols that are safe to inspect right now.
        val (valid, invalid) = symbols.partition { it.validate() }

        // @Validated only targets classes, so filter down before generating.
        valid.filterIsInstance<KSClassDeclaration>().forEach { classDecl ->
            generateValidator(classDecl)
        }

        // Handing back the unresolved symbols tells KSP to retry them on the next round
        // instead of silently dropping them.
        return invalid.toList()
    }

    /**
     * Emits a `<ClassName>Validator.kt` file containing an object that implements
     * `Validator<ClassName>`, with a `validate` function built from the per-parameter checks
     * in [emitPropertyChecks].
     */
    private fun generateValidator(classDecl: KSClassDeclaration) {
        val className = classDecl.toClassName()
        val validatorName = "${className.simpleName}Validator"
        val fileSpec = FileSpec.builder(className.packageName, validatorName)

        val validateFun = FunSpec.builder("validate")
            .addModifiers(com.squareup.kotlinpoet.KModifier.OVERRIDE)
            .addParameter("target", className)
            .returns(com.squareup.kotlinpoet.ClassName(RUNTIME_PACKAGE, "ValidationResult"))

        val code = CodeBlock.builder()

        // A constraint annotation with no explicit use-site target defaults to the
        // constructor *parameter* and is only visible via `KSValueParameter.annotations`;
        // one written `@field:X` (or `@property:X`) attaches to the property/field instead
        // and is only visible via `KSPropertyDeclaration.annotations`. Since either style is
        // valid call-site syntax, merge both sources per property rather than picking one.
        val propertiesByName = classDecl.getDeclaredProperties().associateBy { it.simpleName.asString() }
        classDecl.primaryConstructor?.parameters.orEmpty().forEach { parameter ->
            val propName = parameter.name?.asString() ?: return@forEach
            val property = propertiesByName[propName]
            val annotations = parameter.annotations + (property?.annotations ?: emptySequence())
            emitPropertyChecks(propName, parameter.type.resolve().nullability, annotations, code)
        }

        // Every check above throws on failure, so reaching this point means the target is valid.
        code.addStatement("return %T.valid", com.squareup.kotlinpoet.ClassName(RUNTIME_PACKAGE, "ValidationResult"))
        validateFun.addCode(code.build())

        val validatorObject = TypeSpec.objectBuilder(validatorName)
            .addSuperinterface(
                com.squareup.kotlinpoet.ClassName(RUNTIME_PACKAGE, "Validator")
                    .parameterizedBy(className)
            )
            .addFunction(validateFun.build())
            .build()

        fileSpec.addType(validatorObject)

        val containingFile = classDecl.containingFile
        val dependencies = if (containingFile != null) {
            Dependencies(aggregating = false, containingFile)
        } else {
            Dependencies(aggregating = false)
        }

        fileSpec.build().writeTo(codeGenerator, dependencies)
    }

    /**
     * Appends an `if (...) throw ValidationException(...)` block for each constraint
     * annotation in [annotations], using [nullability] to decide the null-safe form of
     * each check.
     *
     * Checks are emitted in annotation declaration order and each throws immediately on
     * failure, so at most one violation is ever reported per `validate` call.
     */
    private fun emitPropertyChecks(
        propName: String,
        nullability: Nullability,
        annotations: Sequence<KSAnnotation>,
        code: CodeBlock.Builder,
    ) {
        val propAccess = "target.$propName"
        val isNullable = nullability == Nullability.NULLABLE

        annotations.forEach { annotation ->
            // Match on the annotation's actual *declared* name, not `annotation.shortName`
            // (which reflects whatever import alias the call site happens to use — e.g. a
            // file mixing `numeric.long.Min` and `numeric.int.Min` must alias one of them,
            // and shortName would then read "LongMin" instead of "Min").
            val declaration = annotation.annotationType.resolve().declaration
            val annotationName = declaration.simpleName.asString()
            val qualifiedName = declaration.qualifiedName?.asString()
            val isStringAnnotation = qualifiedName?.startsWith("$STRING_ANNOTATIONS_PACKAGE.") == true
            when (annotationName) {
                "Range" -> {
                    val min = rawArg(annotation, "min") ?: return@forEach
                    val max = rawArg(annotation, "max") ?: return@forEach
                    val minLiteral = numberLiteral(min)
                    val maxLiteral = numberLiteral(max)
                    val customMessage = stringArg(annotation, "message")?.takeIf { it.isNotEmpty() }

                    val minMessage = customMessage ?: "must be at least $min"
                    val minAccess = if (isNullable) {
                        "$propAccess?.let { it < $minLiteral } == true"
                    } else {
                        "$propAccess < $minLiteral"
                    }
                    code.beginControlFlow("if ($minAccess)")
                    throwViolation(code, propName, minMessage)
                    code.endControlFlow()

                    val maxMessage = customMessage ?: "must be at most $max"
                    val maxAccess = if (isNullable) {
                        "$propAccess?.let { it > $maxLiteral } == true"
                    } else {
                        "$propAccess > $maxLiteral"
                    }
                    code.beginControlFlow("if ($maxAccess)")
                    throwViolation(code, propName, maxMessage)
                    code.endControlFlow()
                }
                "Pattern" -> {
                    val regex = stringArg(annotation, "regex") ?: ".*"
                    val message = stringArg(annotation, "message")
                        ?.takeIf { it.isNotEmpty() }
                        ?: "must match pattern $regex"
                    if (isNullable) {
                        code.beginControlFlow("if ($propAccess != null && !Regex(%S).matches($propAccess))", regex)
                    } else {
                        code.beginControlFlow("if (!Regex(%S).matches($propAccess))", regex)
                    }
                    throwViolation(code, propName, message)
                    code.endControlFlow()
                }
                "Distinct" -> if (isStringAnnotation) {
                    val values = stringListArg(annotation, "values") ?: emptyList()
                    val message = stringArg(annotation, "message")
                        ?.takeIf { it.isNotEmpty() }
                        ?: "must be one of $values"
                    val allowed = stringSetLiteral(values)
                    if (isNullable) {
                        code.beginControlFlow("if ($propAccess != null && $propAccess !in %L)", allowed)
                    } else {
                        code.beginControlFlow("if ($propAccess !in %L)", allowed)
                    }
                    throwViolation(code, propName, message)
                    code.endControlFlow()
                } else {
                    val values = rawListArg(annotation, "values") ?: emptyList()
                    val message = stringArg(annotation, "message")
                        ?.takeIf { it.isNotEmpty() }
                        ?: "must be one of $values"
                    val allowed = numberSetLiteral(values)
                    if (isNullable) {
                        code.beginControlFlow("if ($propAccess != null && $propAccess !in %L)", allowed)
                    } else {
                        code.beginControlFlow("if ($propAccess !in %L)", allowed)
                    }
                    throwViolation(code, propName, message)
                    code.endControlFlow()
                }
            }
        }
    }

    /**
     * Renders a boxed numeric constant ([Int], [Long], [Double], [Float], [Short], or [Byte])
     * as Kotlin source that reproduces that exact type — e.g. `5L` for a `Long`, `(5).toShort()`
     * for a `Short` — since `Short`/`Byte` have no literal suffix of their own.
     */
    private fun numberLiteral(value: Any): String = when (value) {
        is Long -> "${value}L"
        is Float -> "${value}f"
        is Short -> "($value).toShort()"
        is Byte -> "($value).toByte()"
        else -> "$value"
    }

    /** Builds a `setOf("a", "b", ...)` expression from string constants, safely escaped via `%S`. */
    private fun stringSetLiteral(values: List<String>): CodeBlock {
        val builder = CodeBlock.builder().add("setOf(")
        values.forEachIndexed { index, value ->
            if (index > 0) builder.add(", ")
            builder.add("%S", value)
        }
        return builder.add(")").build()
    }

    /** Builds a `setOf(...)` expression from boxed numeric constants, typed via [numberLiteral]. */
    private fun numberSetLiteral(values: List<Any>): CodeBlock {
        val builder = CodeBlock.builder().add("setOf(")
        values.forEachIndexed { index, value ->
            if (index > 0) builder.add(", ")
            builder.add(numberLiteral(value))
        }
        return builder.add(")").build()
    }

    /** Emits `throw ValidationException(ValidationResult(listOf(ValidationError(field, message))))`. */
    private fun throwViolation(code: CodeBlock.Builder, field: String, message: String) {
        code.addStatement(
            "throw %T(%T(listOf(%T(%S, %S))))",
            com.squareup.kotlinpoet.ClassName(RUNTIME_PACKAGE, "ValidationException"),
            com.squareup.kotlinpoet.ClassName(RUNTIME_PACKAGE, "ValidationResult"),
            errorType(),
            field,
            message,
        )
    }

    private fun errorType() = com.squareup.kotlinpoet.ClassName(RUNTIME_PACKAGE, "ValidationError")

    /** Reads a `String`-typed argument named [name] off [annotation], or `null` if absent. */
    private fun stringArg(annotation: KSAnnotation, name: String): String? =
        (annotation.arguments.find { it.name?.asString() == name } as KSValueArgument?)?.value as? String

    /** Reads a boxed numeric argument named [name] off [annotation], or `null` if absent. */
    private fun rawArg(annotation: KSAnnotation, name: String): Any? =
        (annotation.arguments.find { it.name?.asString() == name } as KSValueArgument?)?.value

    /** Reads an `Array<String>`-typed argument named [name] off [annotation], or `null` if absent. */
    @Suppress("UNCHECKED_CAST")
    private fun stringListArg(annotation: KSAnnotation, name: String): List<String>? =
        (annotation.arguments.find { it.name?.asString() == name } as KSValueArgument?)?.value as? List<String>

    /**
     * Reads a numeric array-typed argument (`IntArray`, `LongArray`, `DoubleArray`,
     * `FloatArray`, `ShortArray`, or `ByteArray`) named [name] off [annotation], or `null`
     * if absent. KSP represents each element with its native boxed type.
     */
    @Suppress("UNCHECKED_CAST")
    private fun rawListArg(annotation: KSAnnotation, name: String): List<Any>? =
        (annotation.arguments.find { it.name?.asString() == name } as KSValueArgument?)?.value as? List<Any>
}

/** KotlinPoet's `ParameterizedTypeName.Companion.parameterizedBy` isn't imported directly to avoid a name clash. */
private fun com.squareup.kotlinpoet.ClassName.parameterizedBy(vararg typeArgs: com.squareup.kotlinpoet.TypeName) =
    com.squareup.kotlinpoet.ParameterizedTypeName.Companion.run {
        this@parameterizedBy.parameterizedBy(*typeArgs)
    }
